-- Migration number: 0001 	 2026-03-29T06:52:09.487Z
CREATE TABLE products (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  image TEXT,
  price REAL NOT NULL,
  stock INTEGER NOT NULL,
  is_featured INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
